WIP: feat: Add support for X3 Ultra
squishykid/solax pull request #147
Opened 2024-03-31 07:35 UTC by Th3Link

2024-04-09 18:45 UTC, Th3Link commented
This will close #146
I've published my quick and dirty tool to help a bit with data interpretation based on the cloud data as well as a data playback, that can be found here: https://github.com/Th3Link/solax-interpretation-tools

2024-04-28 18:42 UTC, Darsstar requested changes

2024-04-28 18:42 UTC, Darsstar commented on solax/inverters/x3_ultra.py
> +            "Battery Remaining Energy": (106, Measurement(Units.KWH), div10),
```suggestion
            "Battery Remaining Energy": (106, Measurement(Units.KWH, storage=True), div10),
```

2024-04-30 08:47 UTC, Darsstar approved these changes

2024-06-01 18:52 UTC, Th3Link commented
Do I need to do something to get it merged?

2024-06-05 10:59 UTC, merged

2024-06-05 10:59 UTC, squishykid commented
Looks good to me! I can make a new release