Fix X1 Hybrid Gen4 support with new firmware
squishykid/solax pull request #164
Opened 2024-06-23 04:06 UTC by nazar-pc

Fixes https://github.com/squishykid/solax/issues/161, new firmware just has a bunch more zeroes on this inverter.
The whole approach wiht counting those is flawed though in my opinion judging by recent PRs. Maybe minimum is okay, but maximum clearly can change in newer firmwares.

2024-08-13 16:09 UTC, MatthieuCoder commented
This is appending to me too

2024-09-13 00:35 UTC, squishykid commented
Hi, thank you so much for raising a PR. Apologies for the late response.

Can you please add a test case which exercises this new behavior?

This recently merged PR can serve as an example for adding a new test fixture: https://github.com/squishykid/solax/pull/167/files#diff-5dbc88d6e5c3615caf10e32a9d6fc6ff683f5b5814948928cb84c3ab91c038b6

When you create an 'InverterUnderTest' in fixtures.py, just use the existing X1 Hybrid G4 inverter.

2024-09-13 00:35 UTC, squishykid requested changes
As discussed in the comment, please add some tests to validate the new schema.

2024-09-13 21:49 UTC, nazar-pc commented
This is a dead simple change, not sure it is actually required to have a whole test just for this. I'd argue checking the length of `data` is useless to begin with, if it wasn't present then this PR wouldn't be necessary. They just decided to add more zeroes in newer firmware and I suspect there will be more people coming over time with other inverters showing the same behavior with newer firmware on them.

2024-11-23 14:42 UTC, squishykid commented
closing this because #176 has been merged instead.

2024-11-23 14:42 UTC, closed without merging